name: Backend CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: 13.219.99.78
        username: jesse
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/home/jesse/backend"

    - name: Restart backend server
      uses: appleboy/ssh-action@master
      with:
        host: 13.219.99.78
        username: jesse
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/jesse/backend
          npm install
          pm2 restart app || pm2 start index.js --name app
